/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoiceDetectorRouteImport } from './routes/_authenticated/voice-detector'
import { Route as AuthenticatedUrlAnalyzerRouteImport } from './routes/_authenticated/url-analyzer'
import { Route as AuthenticatedScamDetectorRouteImport } from './routes/_authenticated/scam-detector'
import { Route as AuthenticatedQrAnalyzerRouteImport } from './routes/_authenticated/qr-analyzer'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedEmailAnalyzerRouteImport } from './routes/_authenticated/email-analyzer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatAnalyzerRouteImport } from './routes/_authenticated/chat-analyzer'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceDetectorRoute =
  AuthenticatedVoiceDetectorRouteImport.update({
    id: '/voice-detector',
    path: '/voice-detector',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUrlAnalyzerRoute =
  AuthenticatedUrlAnalyzerRouteImport.update({
    id: '/url-analyzer',
    path: '/url-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScamDetectorRoute =
  AuthenticatedScamDetectorRouteImport.update({
    id: '/scam-detector',
    path: '/scam-detector',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQrAnalyzerRoute = AuthenticatedQrAnalyzerRouteImport.update({
  id: '/qr-analyzer',
  path: '/qr-analyzer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailAnalyzerRoute =
  AuthenticatedEmailAnalyzerRouteImport.update({
    id: '/email-analyzer',
    path: '/email-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatAnalyzerRoute =
  AuthenticatedChatAnalyzerRouteImport.update({
    id: '/chat-analyzer',
    path: '/chat-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof AuthenticatedChatRoute
  '/chat-analyzer': typeof AuthenticatedChatAnalyzerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-analyzer': typeof AuthenticatedEmailAnalyzerRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/qr-analyzer': typeof AuthenticatedQrAnalyzerRoute
  '/scam-detector': typeof AuthenticatedScamDetectorRoute
  '/url-analyzer': typeof AuthenticatedUrlAnalyzerRoute
  '/voice-detector': typeof AuthenticatedVoiceDetectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof AuthenticatedChatRoute
  '/chat-analyzer': typeof AuthenticatedChatAnalyzerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-analyzer': typeof AuthenticatedEmailAnalyzerRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/qr-analyzer': typeof AuthenticatedQrAnalyzerRoute
  '/scam-detector': typeof AuthenticatedScamDetectorRoute
  '/url-analyzer': typeof AuthenticatedUrlAnalyzerRoute
  '/voice-detector': typeof AuthenticatedVoiceDetectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/chat-analyzer': typeof AuthenticatedChatAnalyzerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-analyzer': typeof AuthenticatedEmailAnalyzerRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/qr-analyzer': typeof AuthenticatedQrAnalyzerRoute
  '/_authenticated/scam-detector': typeof AuthenticatedScamDetectorRoute
  '/_authenticated/url-analyzer': typeof AuthenticatedUrlAnalyzerRoute
  '/_authenticated/voice-detector': typeof AuthenticatedVoiceDetectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/chat'
    | '/chat-analyzer'
    | '/dashboard'
    | '/email-analyzer'
    | '/knowledge'
    | '/learn'
    | '/qr-analyzer'
    | '/scam-detector'
    | '/url-analyzer'
    | '/voice-detector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/chat'
    | '/chat-analyzer'
    | '/dashboard'
    | '/email-analyzer'
    | '/knowledge'
    | '/learn'
    | '/qr-analyzer'
    | '/scam-detector'
    | '/url-analyzer'
    | '/voice-detector'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/chat'
    | '/_authenticated/chat-analyzer'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-analyzer'
    | '/_authenticated/knowledge'
    | '/_authenticated/learn'
    | '/_authenticated/qr-analyzer'
    | '/_authenticated/scam-detector'
    | '/_authenticated/url-analyzer'
    | '/_authenticated/voice-detector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice-detector': {
      id: '/_authenticated/voice-detector'
      path: '/voice-detector'
      fullPath: '/voice-detector'
      preLoaderRoute: typeof AuthenticatedVoiceDetectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/url-analyzer': {
      id: '/_authenticated/url-analyzer'
      path: '/url-analyzer'
      fullPath: '/url-analyzer'
      preLoaderRoute: typeof AuthenticatedUrlAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scam-detector': {
      id: '/_authenticated/scam-detector'
      path: '/scam-detector'
      fullPath: '/scam-detector'
      preLoaderRoute: typeof AuthenticatedScamDetectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-analyzer': {
      id: '/_authenticated/qr-analyzer'
      path: '/qr-analyzer'
      fullPath: '/qr-analyzer'
      preLoaderRoute: typeof AuthenticatedQrAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-analyzer': {
      id: '/_authenticated/email-analyzer'
      path: '/email-analyzer'
      fullPath: '/email-analyzer'
      preLoaderRoute: typeof AuthenticatedEmailAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat-analyzer': {
      id: '/_authenticated/chat-analyzer'
      path: '/chat-analyzer'
      fullPath: '/chat-analyzer'
      preLoaderRoute: typeof AuthenticatedChatAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedChatAnalyzerRoute: typeof AuthenticatedChatAnalyzerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailAnalyzerRoute: typeof AuthenticatedEmailAnalyzerRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedQrAnalyzerRoute: typeof AuthenticatedQrAnalyzerRoute
  AuthenticatedScamDetectorRoute: typeof AuthenticatedScamDetectorRoute
  AuthenticatedUrlAnalyzerRoute: typeof AuthenticatedUrlAnalyzerRoute
  AuthenticatedVoiceDetectorRoute: typeof AuthenticatedVoiceDetectorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedChatAnalyzerRoute: AuthenticatedChatAnalyzerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailAnalyzerRoute: AuthenticatedEmailAnalyzerRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedQrAnalyzerRoute: AuthenticatedQrAnalyzerRoute,
  AuthenticatedScamDetectorRoute: AuthenticatedScamDetectorRoute,
  AuthenticatedUrlAnalyzerRoute: AuthenticatedUrlAnalyzerRoute,
  AuthenticatedVoiceDetectorRoute: AuthenticatedVoiceDetectorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
