/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoiceDetectorRouteImport } from './routes/_authenticated/voice-detector'
import { Route as AuthenticatedScamDetectorRouteImport } from './routes/_authenticated/scam-detector'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedEmailAnalyzerRouteImport } from './routes/_authenticated/email-analyzer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatAnalyzerRouteImport } from './routes/_authenticated/chat-analyzer'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceDetectorRoute =
  AuthenticatedVoiceDetectorRouteImport.update({
    id: '/voice-detector',
    path: '/voice-detector',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScamDetectorRoute =
  AuthenticatedScamDetectorRouteImport.update({
    id: '/scam-detector',
    path: '/scam-detector',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailAnalyzerRoute =
  AuthenticatedEmailAnalyzerRouteImport.update({
    id: '/email-analyzer',
    path: '/email-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatAnalyzerRoute =
  AuthenticatedChatAnalyzerRouteImport.update({
    id: '/chat-analyzer',
    path: '/chat-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/chat-analyzer': typeof AuthenticatedChatAnalyzerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-analyzer': typeof AuthenticatedEmailAnalyzerRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/scam-detector': typeof AuthenticatedScamDetectorRoute
  '/voice-detector': typeof AuthenticatedVoiceDetectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/chat-analyzer': typeof AuthenticatedChatAnalyzerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-analyzer': typeof AuthenticatedEmailAnalyzerRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/scam-detector': typeof AuthenticatedScamDetectorRoute
  '/voice-detector': typeof AuthenticatedVoiceDetectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/chat-analyzer': typeof AuthenticatedChatAnalyzerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-analyzer': typeof AuthenticatedEmailAnalyzerRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/scam-detector': typeof AuthenticatedScamDetectorRoute
  '/_authenticated/voice-detector': typeof AuthenticatedVoiceDetectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/chat-analyzer'
    | '/dashboard'
    | '/email-analyzer'
    | '/learn'
    | '/scam-detector'
    | '/voice-detector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/chat-analyzer'
    | '/dashboard'
    | '/email-analyzer'
    | '/learn'
    | '/scam-detector'
    | '/voice-detector'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/chat-analyzer'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-analyzer'
    | '/_authenticated/learn'
    | '/_authenticated/scam-detector'
    | '/_authenticated/voice-detector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice-detector': {
      id: '/_authenticated/voice-detector'
      path: '/voice-detector'
      fullPath: '/voice-detector'
      preLoaderRoute: typeof AuthenticatedVoiceDetectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scam-detector': {
      id: '/_authenticated/scam-detector'
      path: '/scam-detector'
      fullPath: '/scam-detector'
      preLoaderRoute: typeof AuthenticatedScamDetectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-analyzer': {
      id: '/_authenticated/email-analyzer'
      path: '/email-analyzer'
      fullPath: '/email-analyzer'
      preLoaderRoute: typeof AuthenticatedEmailAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat-analyzer': {
      id: '/_authenticated/chat-analyzer'
      path: '/chat-analyzer'
      fullPath: '/chat-analyzer'
      preLoaderRoute: typeof AuthenticatedChatAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedChatAnalyzerRoute: typeof AuthenticatedChatAnalyzerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailAnalyzerRoute: typeof AuthenticatedEmailAnalyzerRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedScamDetectorRoute: typeof AuthenticatedScamDetectorRoute
  AuthenticatedVoiceDetectorRoute: typeof AuthenticatedVoiceDetectorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedChatAnalyzerRoute: AuthenticatedChatAnalyzerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailAnalyzerRoute: AuthenticatedEmailAnalyzerRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedScamDetectorRoute: AuthenticatedScamDetectorRoute,
  AuthenticatedVoiceDetectorRoute: AuthenticatedVoiceDetectorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
